const FilterConstants = {
  UPDATE_BOUNDS: 'UPDATE_BOUNDS',
  UPDATE_SEARCH_STATUS: 'UPDATE_SEARCH_STATUS',
  UPDATE_SMOKER: 'UPDATE_SMOKER',
  UPDATE_PET: 'UPDATE_PET',
  UPDATE_DIET: 'UPDATE_DIET',
  UPDATE_MIN: 'UPDATE_BUDGET',
};

export default FilterConstants;
