const ProfileConstants = {
  PROFILES_RECEIVED: 'PROFILES_RECEIVED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  DELETE_PROFILE: 'DELETE_PROFILE',
  CLEAR_PROFILES: 'CLEAR_PROFILES',
  UPDATE_HOVERED: 'UPDATE_HOVERED',
  UPDATE_LOC: 'UPDATE_LOC',
};

export default ProfileConstants;
