const UserConstants = {
  RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER',
  REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
  ERRORS: 'ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
};

export default UserConstants;
